### ISSUE TITLE
Default Avatar settings bugged

### ISSUE THREAD

**Issue by brianrc** [timersys/facebook-login#8] opened 2015-12-31 23:35 UTC
When you log in through Facebook (and you're a site admin) the WP Admin -> Setting -> Discussion -> Default Avatar settings are bugged. All the options become your Facebook avatar. See screenshot.

![default-avatar](https://cloud.githubusercontent.com/assets/573939/12069093/a938541e-afec-11e5-88ac-3477bfa5e12a.png)

**Comment by timersys** [comment] 2016-01-13 14:46
Can't reproduce, probably fixed in https://github.com/timersys/facebook-login/commit/332396cdfa84f771c4ca3546579ec7cafda8457a

**Closed as completed by timersys** 2016-01-13 14:46 UTC

**Comment by brianrc** [comment] 2016-01-13 19:07
Confirmed fixed. Thank you!
